#!/usr/bin/env python
import os,sys
import argparse

cwd='/'.join(os.path.realpath(sys.argv[0]).split('/')[:-1])
os.chdir(cwd)

parser = argparse.ArgumentParser(description='Regionfs command line interface')
subparsers = parser.add_subparsers()
parser_node = subparsers.add_parser('node')

parser_node.add_argument('action', metavar='A', nargs=1, choices=('start', 'stop'), help='The action to be performed on nodes.')
parser_node.add_argument('-l','--list', metavar='host,host,...', nargs=1, help='The target node hosts spited by ,. Default is current host.')

def node(args):
    action="./{}-node".format(args.action[0])
    if args.list:
        for n in args.list[0].split(','):
            os.system('ssh {} {}'.format(n,action))
    else:
        os.system(action)

parser_node.set_defaults(func=node)

args = parser.parse_args()
try: #https://stackoverflow.com/a/54161510/4444459
    args.func(args)
except AttributeError:
    parser.parse_args(['--help'])
